# Generated by Django 5.0.4 on 2024-04-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrosbip',
            name='este',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='centrosbip',
            name='norte',
            field=models.FloatField(blank=True),
        ),
    ]
