# Generated by Django 5.0.4 on 2024-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bip', '0002_alter_centrosbip_este_alter_centrosbip_norte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrosbip',
            name='este',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='centrosbip',
            name='norte',
            field=models.FloatField(null=True),
        ),
    ]
